version: "3.9"

services:
  api:
    build: .
    image: stage1-node-api:latest
    container_name: stage1-node-api
    ports:
      - "3000:3000"
    env_file:
      - env.example
    environment:
      - NODE_ENV=production
    restart: unless-stopped

