services:
  mongo:
    image: mongo:7
    container_name: stage5-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: stage5-node-api:latest
    container_name: stage5-node-api
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - ./api/env.example
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - ./api/src:/app/src
      - node_modules_api:/app/node_modules
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: stage5-web:latest
    container_name: stage5-web
    ports:
      - "3001:3000"
    env_file:
      - ./web/env.example
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./web/pages:/app/pages
      - node_modules_web:/app/node_modules
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mongo_data:
  node_modules_api:
  node_modules_web:




